apiVersion: v1
kind: Secret
metadata:
  name: docker-credentials
  namespace: frensapp
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "https://index.docker.io/v1/": {
          "auth": "bmVoZWNvZGVzOmRja3JfcGF0X1lxWVhxb2tycHZHRW1oVVBsOVZuRF9FMldwNA=="
        }
      }
    }
