apiVersion: apps/v1
kind: Deployment
metadata:
  name: frens-app
  namespace: frens
  labels:
    app: frens-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frens-app
  template:
    metadata:
      labels:
        app: frens-app
    spec:
      containers:
        - name: frens-app
          image: your-dockerhub-username/frens-app:latest
          ports:
            - containerPort: 3000
          env:
            - name: RAILS_ENV
              value: "production"
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: frens-app-secret
                  key: database_url
          command: ["bash", "-c"]
          args:
            - |
              bundle exec rails db:migrate && 
              bundle exec rails s -b 0.0.0.0
---
apiVersion: v1
kind: Service
metadata:
  name: frens-app-service
  namespace: frens
spec:
  selector:
    app: frens-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000

