apiVersion: v1
kind: Secret
metadata:
  name: frens-app-secret
  namespace: frens
type: Opaque
stringData:
  database_url: "postgres://postgres:bXlwYXNzd29yZAo=@postgres-service.frens.svc.cluster.local:5432/frens_app_production"

