apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
type: Opaque
data:
  username: postgres
  password: securePassword123
  database: friends
  database-url: postgresql://postgres:securePassword123@postgres-service:5432/friends