apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
type: Opaque
data:
  username: cG9zdGdyZXM=
  password: c2VjdXJlUGFzc3dvcmQxMjM=
  database: ZnJlbnM=
  database-url: cG9zdGdyZXNxbDovL3Bvc3RncmVzOnNlY3VyZVBhc3N3b3JkMTIzQHBvc3RncmVzLXNlcnZpY2U6NTQzMi9mcmllbmRz
  # This decodes to: postgresql://postgres:securePassword123@postgres-service:5432/friends